package com.bikeshare.ncs.bean;

public class NcsDay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.year
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.month
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private String day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.week
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.holiday
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private String holiday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.season
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Integer season;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_day.weather
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private String weather;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.id
     *
     * @return the value of ncs_day.id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.id
     *
     * @param id the value for ncs_day.id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.year
     *
     * @return the value of ncs_day.year
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.year
     *
     * @param year the value for ncs_day.year
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.month
     *
     * @return the value of ncs_day.month
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.month
     *
     * @param month the value for ncs_day.month
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.day
     *
     * @return the value of ncs_day.day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.day
     *
     * @param day the value for ncs_day.day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.week
     *
     * @return the value of ncs_day.week
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.week
     *
     * @param week the value for ncs_day.week
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.holiday
     *
     * @return the value of ncs_day.holiday
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public String getHoliday() {
        return holiday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.holiday
     *
     * @param holiday the value for ncs_day.holiday
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setHoliday(String holiday) {
        this.holiday = holiday == null ? null : holiday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.season
     *
     * @return the value of ncs_day.season
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Integer getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.season
     *
     * @param season the value for ncs_day.season
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setSeason(Integer season) {
        this.season = season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_day.weather
     *
     * @return the value of ncs_day.weather
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_day.weather
     *
     * @param weather the value for ncs_day.weather
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }
}