package com.bikeshare.ncs.bean;

public class NcsHourUsage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.bikeinfo_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long bikeinfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.region_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.day_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long dayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.hour
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Integer hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.temperature
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Double temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.register_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long registerUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.unregister_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long unregisterUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_hour_usage.total_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    private Long totalUsage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.id
     *
     * @return the value of ncs_hour_usage.id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.id
     *
     * @param id the value for ncs_hour_usage.id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.bikeinfo_id
     *
     * @return the value of ncs_hour_usage.bikeinfo_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getBikeinfoId() {
        return bikeinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.bikeinfo_id
     *
     * @param bikeinfoId the value for ncs_hour_usage.bikeinfo_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setBikeinfoId(Long bikeinfoId) {
        this.bikeinfoId = bikeinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.region_id
     *
     * @return the value of ncs_hour_usage.region_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.region_id
     *
     * @param regionId the value for ncs_hour_usage.region_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.day_id
     *
     * @return the value of ncs_hour_usage.day_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getDayId() {
        return dayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.day_id
     *
     * @param dayId the value for ncs_hour_usage.day_id
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setDayId(Long dayId) {
        this.dayId = dayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.hour
     *
     * @return the value of ncs_hour_usage.hour
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.hour
     *
     * @param hour the value for ncs_hour_usage.hour
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.temperature
     *
     * @return the value of ncs_hour_usage.temperature
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.temperature
     *
     * @param temperature the value for ncs_hour_usage.temperature
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.register_usage
     *
     * @return the value of ncs_hour_usage.register_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getRegisterUsage() {
        return registerUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.register_usage
     *
     * @param registerUsage the value for ncs_hour_usage.register_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setRegisterUsage(Long registerUsage) {
        this.registerUsage = registerUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.unregister_usage
     *
     * @return the value of ncs_hour_usage.unregister_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getUnregisterUsage() {
        return unregisterUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.unregister_usage
     *
     * @param unregisterUsage the value for ncs_hour_usage.unregister_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setUnregisterUsage(Long unregisterUsage) {
        this.unregisterUsage = unregisterUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_hour_usage.total_usage
     *
     * @return the value of ncs_hour_usage.total_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public Long getTotalUsage() {
        return totalUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_hour_usage.total_usage
     *
     * @param totalUsage the value for ncs_hour_usage.total_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    public void setTotalUsage(Long totalUsage) {
        this.totalUsage = totalUsage;
    }
}