package com.bikeshare.ncs.bean;

public class NcsRegions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.id
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.areaCode
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.areaName
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.level
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.cityCode
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.center
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private String center;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ncs_region.parentId
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    private Long parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.id
     *
     * @return the value of ncs_region.id
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.id
     *
     * @param id the value for ncs_region.id
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.areaCode
     *
     * @return the value of ncs_region.areaCode
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.areaCode
     *
     * @param areacode the value for ncs_region.areaCode
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.areaName
     *
     * @return the value of ncs_region.areaName
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.areaName
     *
     * @param areaname the value for ncs_region.areaName
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.level
     *
     * @return the value of ncs_region.level
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.level
     *
     * @param level the value for ncs_region.level
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.cityCode
     *
     * @return the value of ncs_region.cityCode
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.cityCode
     *
     * @param citycode the value for ncs_region.cityCode
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.center
     *
     * @return the value of ncs_region.center
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.center
     *
     * @param center the value for ncs_region.center
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setCenter(String center) {
        this.center = center == null ? null : center.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ncs_region.parentId
     *
     * @return the value of ncs_region.parentId
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ncs_region.parentId
     *
     * @param parentid the value for ncs_region.parentId
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }
}