package com.bikeshare.ncs.bean;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.info
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.intro
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.info
     *
     * @return the value of test.info
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.info
     *
     * @param info the value for test.info
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.intro
     *
     * @return the value of test.intro
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.intro
     *
     * @param intro the value for test.intro
     *
     * @mbg.generated Sat Apr 18 21:06:33 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}