package com.bikeshare.ncs.dao;

import com.bikeshare.ncs.bean.BaseRolePrivilege;
import com.bikeshare.ncs.bean.BaseRolePrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    long countByExample(BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int deleteByExample(BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int insert(BaseRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int insertSelective(BaseRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    List<BaseRolePrivilege> selectByExample(BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    BaseRolePrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") BaseRolePrivilege record, @Param("example") BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int updateByExample(@Param("record") BaseRolePrivilege record, @Param("example") BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int updateByPrimaryKeySelective(BaseRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Sun Apr 19 19:08:51 CST 2020
     */
    int updateByPrimaryKey(BaseRolePrivilege record);
}