package com.bikeshare.ncs.dao;

import com.bikeshare.ncs.bean.NcsBikeinfo;
import com.bikeshare.ncs.bean.NcsBikeinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NcsBikeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    long countByExample(NcsBikeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByExample(NcsBikeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insert(NcsBikeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insertSelective(NcsBikeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    List<NcsBikeinfo> selectByExample(NcsBikeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    NcsBikeinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") NcsBikeinfo record, @Param("example") NcsBikeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExample(@Param("record") NcsBikeinfo record, @Param("example") NcsBikeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKeySelective(NcsBikeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_bikeinfo
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKey(NcsBikeinfo record);
}