package com.bikeshare.ncs.dao;

import com.bikeshare.ncs.bean.NcsDay;
import com.bikeshare.ncs.bean.NcsDayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NcsDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    long countByExample(NcsDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByExample(NcsDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insert(NcsDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insertSelective(NcsDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    List<NcsDay> selectByExample(NcsDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    NcsDay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") NcsDay record, @Param("example") NcsDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExample(@Param("record") NcsDay record, @Param("example") NcsDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKeySelective(NcsDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKey(NcsDay record);
}