package com.bikeshare.ncs.dao;

import com.bikeshare.ncs.bean.NcsDayUsage;
import com.bikeshare.ncs.bean.NcsDayUsageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NcsDayUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    long countByExample(NcsDayUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByExample(NcsDayUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insert(NcsDayUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insertSelective(NcsDayUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    List<NcsDayUsage> selectByExample(NcsDayUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    NcsDayUsage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") NcsDayUsage record, @Param("example") NcsDayUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExample(@Param("record") NcsDayUsage record, @Param("example") NcsDayUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKeySelective(NcsDayUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_day_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKey(NcsDayUsage record);
}