package com.bikeshare.ncs.dao;

import com.bikeshare.ncs.bean.NcsHourUsage;
import com.bikeshare.ncs.bean.NcsHourUsageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NcsHourUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    long countByExample(NcsHourUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByExample(NcsHourUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insert(NcsHourUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int insertSelective(NcsHourUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    List<NcsHourUsage> selectByExample(NcsHourUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    NcsHourUsage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") NcsHourUsage record, @Param("example") NcsHourUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByExample(@Param("record") NcsHourUsage record, @Param("example") NcsHourUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKeySelective(NcsHourUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_hour_usage
     *
     * @mbg.generated Fri Apr 24 12:51:23 CST 2020
     */
    int updateByPrimaryKey(NcsHourUsage record);
}