package com.bikeshare.ncs.dao;

import com.bikeshare.ncs.bean.NcsRegions;
import com.bikeshare.ncs.bean.NcsRegionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NcsRegionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    long countByExample(NcsRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int deleteByExample(NcsRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int insert(NcsRegions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int insertSelective(NcsRegions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    List<NcsRegions> selectByExample(NcsRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    NcsRegions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") NcsRegions record, @Param("example") NcsRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int updateByExample(@Param("record") NcsRegions record, @Param("example") NcsRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int updateByPrimaryKeySelective(NcsRegions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ncs_region
     *
     * @mbg.generated Fri Apr 24 20:48:16 CST 2020
     */
    int updateByPrimaryKey(NcsRegions record);
}